FROM node:12.13.1-alpine3.10

LABEL \
  name-to-set="tojacob/node-dev" \
  version="1.0.0" \
  description="This image is used for develop Node.js applications"

ENV NODE_ENV="development"

RUN \
  npm install -g \
  @angular/cli \
  firebase-tools \
  typescript

CMD ["sh"]