FROM node:12.14.0-alpine3.11

LABEL \
  name-to-set="tojacob/js-dev" \
  version="1.0.0" \
  description="This image is used for develop Javascript applications"

ENV NODE_ENV="development"

RUN \
  npm install -g \
  @angular/cli \
  firebase-tools \
  typescript \
  gulp@4.0.2 \
  nodemon

CMD ["sh"]